// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModuleProtocol.proto

package com.zxcc.game.socket.protobuf;

public final class ModuleProtocol {
  private ModuleProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 mod = 1;
    /**
     * <code>optional int32 mod = 1;</code>
     *
     * <pre>
     * 模块号
     * </pre>
     */
    boolean hasMod();
    /**
     * <code>optional int32 mod = 1;</code>
     *
     * <pre>
     * 模块号
     * </pre>
     */
    int getMod();

    // optional int32 cmd = 2;
    /**
     * <code>optional int32 cmd = 2;</code>
     *
     * <pre>
     * 指令值
     * </pre>
     */
    boolean hasCmd();
    /**
     * <code>optional int32 cmd = 2;</code>
     *
     * <pre>
     * 指令值
     * </pre>
     */
    int getCmd();

    // optional int32 csn = 3;
    /**
     * <code>optional int32 csn = 3;</code>
     *
     * <pre>
     * 客服端唯一系列号
     * </pre>
     */
    boolean hasCsn();
    /**
     * <code>optional int32 csn = 3;</code>
     *
     * <pre>
     * 客服端唯一系列号
     * </pre>
     */
    int getCsn();

    // optional int32 state = 4;
    /**
     * <code>optional int32 state = 4;</code>
     *
     * <pre>
     * 压缩等状态标识
     * </pre>
     */
    boolean hasState();
    /**
     * <code>optional int32 state = 4;</code>
     *
     * <pre>
     * 压缩等状态标识
     * </pre>
     */
    int getState();

    // optional int32 ssn = 5;
    /**
     * <code>optional int32 ssn = 5;</code>
     *
     * <pre>
     *服务端唯一系列号
     * </pre>
     */
    boolean hasSsn();
    /**
     * <code>optional int32 ssn = 5;</code>
     *
     * <pre>
     *服务端唯一系列号
     * </pre>
     */
    int getSsn();
  }
  /**
   * Protobuf type {@code com.zxcc.game.socket.protobuf.Header}
   *
   * <pre>
   **
   *消息头
   * </pre>
   */
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }

    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mod_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cmd_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              csn_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              state_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ssn_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Header.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Header> PARSER =
        new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 mod = 1;
    public static final int MOD_FIELD_NUMBER = 1;
    private int mod_;
    /**
     * <code>optional int32 mod = 1;</code>
     *
     * <pre>
     * 模块号
     * </pre>
     */
    public boolean hasMod() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 mod = 1;</code>
     *
     * <pre>
     * 模块号
     * </pre>
     */
    public int getMod() {
      return mod_;
    }

    // optional int32 cmd = 2;
    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <code>optional int32 cmd = 2;</code>
     *
     * <pre>
     * 指令值
     * </pre>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 cmd = 2;</code>
     *
     * <pre>
     * 指令值
     * </pre>
     */
    public int getCmd() {
      return cmd_;
    }

    // optional int32 csn = 3;
    public static final int CSN_FIELD_NUMBER = 3;
    private int csn_;
    /**
     * <code>optional int32 csn = 3;</code>
     *
     * <pre>
     * 客服端唯一系列号
     * </pre>
     */
    public boolean hasCsn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 csn = 3;</code>
     *
     * <pre>
     * 客服端唯一系列号
     * </pre>
     */
    public int getCsn() {
      return csn_;
    }

    // optional int32 state = 4;
    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>optional int32 state = 4;</code>
     *
     * <pre>
     * 压缩等状态标识
     * </pre>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 state = 4;</code>
     *
     * <pre>
     * 压缩等状态标识
     * </pre>
     */
    public int getState() {
      return state_;
    }

    // optional int32 ssn = 5;
    public static final int SSN_FIELD_NUMBER = 5;
    private int ssn_;
    /**
     * <code>optional int32 ssn = 5;</code>
     *
     * <pre>
     *服务端唯一系列号
     * </pre>
     */
    public boolean hasSsn() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 ssn = 5;</code>
     *
     * <pre>
     *服务端唯一系列号
     * </pre>
     */
    public int getSsn() {
      return ssn_;
    }

    private void initFields() {
      mod_ = 0;
      cmd_ = 0;
      csn_ = 0;
      state_ = 0;
      ssn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mod_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, csn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, state_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, ssn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mod_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, csn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ssn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zxcc.game.socket.protobuf.Header}
     *
     * <pre>
     **
     *消息头
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Header.class, Builder.class);
      }

      // Construct using com.zxcc.game.socket.protobuf.ModuleProtocol.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        csn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        ssn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_Header_descriptor;
      }

      public Header getDefaultInstanceForType() {
        return Header.getDefaultInstance();
      }

      public Header build() {
        Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Header buildPartial() {
        Header result = new Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mod_ = mod_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.csn_ = csn_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ssn_ = ssn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Header) {
          return mergeFrom((Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Header other) {
        if (other == Header.getDefaultInstance()) return this;
        if (other.hasMod()) {
          setMod(other.getMod());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasCsn()) {
          setCsn(other.getCsn());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasSsn()) {
          setSsn(other.getSsn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Header) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 mod = 1;
      private int mod_ ;
      /**
       * <code>optional int32 mod = 1;</code>
       *
       * <pre>
       * 模块号
       * </pre>
       */
      public boolean hasMod() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 mod = 1;</code>
       *
       * <pre>
       * 模块号
       * </pre>
       */
      public int getMod() {
        return mod_;
      }
      /**
       * <code>optional int32 mod = 1;</code>
       *
       * <pre>
       * 模块号
       * </pre>
       */
      public Builder setMod(int value) {
        bitField0_ |= 0x00000001;
        mod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mod = 1;</code>
       *
       * <pre>
       * 模块号
       * </pre>
       */
      public Builder clearMod() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mod_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cmd = 2;
      private int cmd_ ;
      /**
       * <code>optional int32 cmd = 2;</code>
       *
       * <pre>
       * 指令值
       * </pre>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cmd = 2;</code>
       *
       * <pre>
       * 指令值
       * </pre>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional int32 cmd = 2;</code>
       *
       * <pre>
       * 指令值
       * </pre>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmd = 2;</code>
       *
       * <pre>
       * 指令值
       * </pre>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        onChanged();
        return this;
      }

      // optional int32 csn = 3;
      private int csn_ ;
      /**
       * <code>optional int32 csn = 3;</code>
       *
       * <pre>
       * 客服端唯一系列号
       * </pre>
       */
      public boolean hasCsn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 csn = 3;</code>
       *
       * <pre>
       * 客服端唯一系列号
       * </pre>
       */
      public int getCsn() {
        return csn_;
      }
      /**
       * <code>optional int32 csn = 3;</code>
       *
       * <pre>
       * 客服端唯一系列号
       * </pre>
       */
      public Builder setCsn(int value) {
        bitField0_ |= 0x00000004;
        csn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 csn = 3;</code>
       *
       * <pre>
       * 客服端唯一系列号
       * </pre>
       */
      public Builder clearCsn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        csn_ = 0;
        onChanged();
        return this;
      }

      // optional int32 state = 4;
      private int state_ ;
      /**
       * <code>optional int32 state = 4;</code>
       *
       * <pre>
       * 压缩等状态标识
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 state = 4;</code>
       *
       * <pre>
       * 压缩等状态标识
       * </pre>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>optional int32 state = 4;</code>
       *
       * <pre>
       * 压缩等状态标识
       * </pre>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 state = 4;</code>
       *
       * <pre>
       * 压缩等状态标识
       * </pre>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = 0;
        onChanged();
        return this;
      }

      // optional int32 ssn = 5;
      private int ssn_ ;
      /**
       * <code>optional int32 ssn = 5;</code>
       *
       * <pre>
       *服务端唯一系列号
       * </pre>
       */
      public boolean hasSsn() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 ssn = 5;</code>
       *
       * <pre>
       *服务端唯一系列号
       * </pre>
       */
      public int getSsn() {
        return ssn_;
      }
      /**
       * <code>optional int32 ssn = 5;</code>
       *
       * <pre>
       *服务端唯一系列号
       * </pre>
       */
      public Builder setSsn(int value) {
        bitField0_ |= 0x00000010;
        ssn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ssn = 5;</code>
       *
       * <pre>
       *服务端唯一系列号
       * </pre>
       */
      public Builder clearSsn() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ssn_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zxcc.game.socket.protobuf.Header)
    }

    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zxcc.game.socket.protobuf.Header)
  }

  public interface RequestMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.zxcc.game.socket.protobuf.Header header = 1;
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     */
    Header getHeader();
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     */
    HeaderOrBuilder getHeaderOrBuilder();

    // optional bytes body = 2;
    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 参数值
     * </pre>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 参数值
     * </pre>
     */
    com.google.protobuf.ByteString getBody();

    // optional string httpBody = 3;
    /**
     * <code>optional string httpBody = 3;</code>
     */
    boolean hasHttpBody();
    /**
     * <code>optional string httpBody = 3;</code>
     */
    String getHttpBody();
    /**
     * <code>optional string httpBody = 3;</code>
     */
    com.google.protobuf.ByteString
        getHttpBodyBytes();
  }
  /**
   * Protobuf type {@code com.zxcc.game.socket.protobuf.RequestMsg}
   *
   * <pre>
   **
   *请求协议
   * </pre>
   */
  public static final class RequestMsg extends
      com.google.protobuf.GeneratedMessage
      implements RequestMsgOrBuilder {
    // Use RequestMsg.newBuilder() to construct.
    private RequestMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestMsg defaultInstance;
    public static RequestMsg getDefaultInstance() {
      return defaultInstance;
    }

    public RequestMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              httpBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_RequestMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_RequestMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestMsg.class, Builder.class);
    }

    public static com.google.protobuf.Parser<RequestMsg> PARSER =
        new com.google.protobuf.AbstractParser<RequestMsg>() {
      public RequestMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMsg(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RequestMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.zxcc.game.socket.protobuf.Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private Header header_;
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     */
    public Header getHeader() {
      return header_;
    }
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     */
    public HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    // optional bytes body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 参数值
     * </pre>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 参数值
     * </pre>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    // optional string httpBody = 3;
    public static final int HTTPBODY_FIELD_NUMBER = 3;
    private Object httpBody_;
    /**
     * <code>optional string httpBody = 3;</code>
     */
    public boolean hasHttpBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string httpBody = 3;</code>
     */
    public String getHttpBody() {
      Object ref = httpBody_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          httpBody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string httpBody = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHttpBodyBytes() {
      Object ref = httpBody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        httpBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      header_ = Header.getDefaultInstance();
      body_ = com.google.protobuf.ByteString.EMPTY;
      httpBody_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHttpBodyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHttpBodyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RequestMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RequestMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RequestMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RequestMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zxcc.game.socket.protobuf.RequestMsg}
     *
     * <pre>
     **
     *请求协议
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RequestMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_RequestMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_RequestMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestMsg.class, Builder.class);
      }

      // Construct using com.zxcc.game.socket.protobuf.ModuleProtocol.RequestMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        httpBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_RequestMsg_descriptor;
      }

      public RequestMsg getDefaultInstanceForType() {
        return RequestMsg.getDefaultInstance();
      }

      public RequestMsg build() {
        RequestMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestMsg buildPartial() {
        RequestMsg result = new RequestMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.httpBody_ = httpBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestMsg) {
          return mergeFrom((RequestMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestMsg other) {
        if (other == RequestMsg.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        if (other.hasHttpBody()) {
          bitField0_ |= 0x00000004;
          httpBody_ = other.httpBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.zxcc.game.socket.protobuf.Header header = 1;
      private Header header_ = Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public Builder setHeader(Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public Builder setHeader(
          Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public Builder mergeHeader(Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != Header.getDefaultInstance()) {
            header_ =
              Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      public HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Header, Header.Builder, HeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // optional bytes body = 2;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 参数值
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 参数值
       * </pre>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 参数值
       * </pre>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 参数值
       * </pre>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // optional string httpBody = 3;
      private Object httpBody_ = "";
      /**
       * <code>optional string httpBody = 3;</code>
       */
      public boolean hasHttpBody() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string httpBody = 3;</code>
       */
      public String getHttpBody() {
        Object ref = httpBody_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          httpBody_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string httpBody = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHttpBodyBytes() {
        Object ref = httpBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          httpBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string httpBody = 3;</code>
       */
      public Builder setHttpBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        httpBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string httpBody = 3;</code>
       */
      public Builder clearHttpBody() {
        bitField0_ = (bitField0_ & ~0x00000004);
        httpBody_ = getDefaultInstance().getHttpBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string httpBody = 3;</code>
       */
      public Builder setHttpBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        httpBody_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zxcc.game.socket.protobuf.RequestMsg)
    }

    static {
      defaultInstance = new RequestMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zxcc.game.socket.protobuf.RequestMsg)
  }

  public interface ResponseMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.zxcc.game.socket.protobuf.Header header = 1;
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     *
     * <pre>
     **
     *返回代码
     * </pre>
     */
    boolean hasHeader();
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     *
     * <pre>
     **
     *返回代码
     * </pre>
     */
    Header getHeader();
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     *
     * <pre>
     **
     *返回代码
     * </pre>
     */
    HeaderOrBuilder getHeaderOrBuilder();

    // optional int32 code = 2;
    /**
     * <code>optional int32 code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>optional int32 code = 2;</code>
     */
    int getCode();

    // optional bytes body = 3;
    /**
     * <code>optional bytes body = 3;</code>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 3;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code com.zxcc.game.socket.protobuf.ResponseMsg}
   *
   * <pre>
   **
   *响应协议
   *
   *
   *Code 对应的值和意义 ：
   *
   *参数不能为空
   *int ILLEGAL_NULL_PARAM = -252;
   *
   *返回值异常返回值必须是Protobuf对象或者是基本类型
   *int ILLEGAL_RETURN_TYPE_PARAM = -253;
   *
   *参数异常参数必须是Protobuf对象或者是基本类型的包装类
   *int ILLEGAL_TYPE_PARAM = -254;
   *
   *未知错误
   *int UNKNOW_ERROR = -255;
   *
   *参数异常参数不是对应的protobuf参数
   *int ILLEGAL_PROTOBUF_PARAM = -256;
   *
   *返回参数是protobuf类型
   *int PROTOBUF = 0;
   *
   *返回基础类型
   *int ISPRIMITIVE = 1;
   *
   *返回参数是空
   *int NULL = 2;
   * </pre>
   */
  public static final class ResponseMsg extends
      com.google.protobuf.GeneratedMessage
      implements ResponseMsgOrBuilder {
    // Use ResponseMsg.newBuilder() to construct.
    private ResponseMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseMsg defaultInstance;
    public static ResponseMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseMsg.class, Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseMsg> PARSER =
        new com.google.protobuf.AbstractParser<ResponseMsg>() {
      public ResponseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMsg(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ResponseMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.zxcc.game.socket.protobuf.Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private Header header_;
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     *
     * <pre>
     **
     *返回代码
     * </pre>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     *
     * <pre>
     **
     *返回代码
     * </pre>
     */
    public Header getHeader() {
      return header_;
    }
    /**
     * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
     *
     * <pre>
     **
     *返回代码
     * </pre>
     */
    public HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    // optional int32 code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>optional int32 code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    // optional bytes body = 3;
    public static final int BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 3;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes body = 3;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private void initFields() {
      header_ = Header.getDefaultInstance();
      code_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ResponseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ResponseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ResponseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ResponseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ResponseMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zxcc.game.socket.protobuf.ResponseMsg}
     *
     * <pre>
     **
     *响应协议
     *
     *
     *Code 对应的值和意义 ：
     *
     *参数不能为空
     *int ILLEGAL_NULL_PARAM = -252;
     *
     *返回值异常返回值必须是Protobuf对象或者是基本类型
     *int ILLEGAL_RETURN_TYPE_PARAM = -253;
     *
     *参数异常参数必须是Protobuf对象或者是基本类型的包装类
     *int ILLEGAL_TYPE_PARAM = -254;
     *
     *未知错误
     *int UNKNOW_ERROR = -255;
     *
     *参数异常参数不是对应的protobuf参数
     *int ILLEGAL_PROTOBUF_PARAM = -256;
     *
     *返回参数是protobuf类型
     *int PROTOBUF = 0;
     *
     *返回基础类型
     *int ISPRIMITIVE = 1;
     *
     *返回参数是空
     *int NULL = 2;
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ResponseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseMsg.class, Builder.class);
      }

      // Construct using com.zxcc.game.socket.protobuf.ModuleProtocol.ResponseMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ModuleProtocol.internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_descriptor;
      }

      public ResponseMsg getDefaultInstanceForType() {
        return ResponseMsg.getDefaultInstance();
      }

      public ResponseMsg build() {
        ResponseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResponseMsg buildPartial() {
        ResponseMsg result = new ResponseMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseMsg) {
          return mergeFrom((ResponseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseMsg other) {
        if (other == ResponseMsg.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.zxcc.game.socket.protobuf.Header header = 1;
      private Header header_ = Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public Builder setHeader(Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public Builder setHeader(
          Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public Builder mergeHeader(Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != Header.getDefaultInstance()) {
            header_ =
              Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      public HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>optional .com.zxcc.game.socket.protobuf.Header header = 1;</code>
       *
       * <pre>
       **
       *返回代码
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Header, Header.Builder, HeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // optional int32 code = 2;
      private int code_ ;
      /**
       * <code>optional int32 code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      // optional bytes body = 3;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 3;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes body = 3;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 3;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 3;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000004);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zxcc.game.socket.protobuf.ResponseMsg)
    }

    static {
      defaultInstance = new ResponseMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zxcc.game.socket.protobuf.ResponseMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zxcc_game_socket_protobuf_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zxcc_game_socket_protobuf_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zxcc_game_socket_protobuf_RequestMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zxcc_game_socket_protobuf_RequestMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024ModuleProtocol.proto\022\035com.zxcc.game.so" +
      "cket.protobuf\"K\n\006Header\022\013\n\003mod\030\001 \001(\005\022\013\n\003" +
      "cmd\030\002 \001(\005\022\013\n\003csn\030\003 \001(\005\022\r\n\005state\030\004 \001(\005\022\013\n" +
      "\003ssn\030\005 \001(\005\"c\n\nRequestMsg\0225\n\006header\030\001 \001(\013" +
      "2%.com.zxcc.game.socket.protobuf.Header\022" +
      "\014\n\004body\030\002 \001(\014\022\020\n\010httpBody\030\003 \001(\t\"`\n\013Respo" +
      "nseMsg\0225\n\006header\030\001 \001(\0132%.com.zxcc.game.s" +
      "ocket.protobuf.Header\022\014\n\004code\030\002 \001(\005\022\014\n\004b" +
      "ody\030\003 \001(\014B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zxcc_game_socket_protobuf_Header_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zxcc_game_socket_protobuf_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zxcc_game_socket_protobuf_Header_descriptor,
              new String[] { "Mod", "Cmd", "Csn", "State", "Ssn", });
          internal_static_com_zxcc_game_socket_protobuf_RequestMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zxcc_game_socket_protobuf_RequestMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zxcc_game_socket_protobuf_RequestMsg_descriptor,
              new String[] { "Header", "Body", "HttpBody", });
          internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zxcc_game_socket_protobuf_ResponseMsg_descriptor,
              new String[] { "Header", "Code", "Body", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
